### ISSUE TITLE
[Bug]: Wrong value in provided theme.css

### ISSUE THREAD

**Issue by yhabib** [untitleduico/react#105]
### Prerequisites

- [x] I have searched existing issues to ensure this bug hasn't been reported already
- [x] I have tested this with the latest version of the components

### Bug description

In the [manual installation notes](https://www.untitledui.com/react/docs/installation#manual-installation), you provide the contents for the theme file, which includes the following line:  
```
--color-transparent: 255 rgb(255 255 0);
```

I couldn't find any matches for this in your repository, so I assume it is a bug.

### Steps to reproduce

1. Go to https://www.untitledui.com/react/docs/installation#manual-installation
2. Scroll to the "Create a custom Tailwind CSS configuration" section
3. Open the section and search for `--color-transparent`

### Expected behavior

Based on this [match](https://github.com/search?q=repo%3Auntitleduico%2Freact%20--color-transparent&type=code):
```
--color-transparent: rgb(0 0 0 / 0);
```

### Actual behavior

```
--color-transparent: 255 rgb(255 255 0);
```

### Code example

```tsx

```

### Browser

Chrome

### Device type

Desktop

### Console errors

```shell

```

### Accessibility impact

- [ ] This bug affects keyboard navigation
- [ ] This bug affects screen reader users
- [ ] This bug affects focus management
- [ ] This bug affects color contrast or visual accessibility

**Comment by deebov** [comment]
Hey @yhabib, thanks for reporting this!

This issue should be fixed now! Let us know if anything else comes up. 

I'll close this issue for now.

**Comment by isaacwilliams** [comment]
@deebov I think this is still incorrect, at least in the manual installation page:

https://www.untitledui.com/react/docs/installation#manual-installation

```
/* BASE COLOR */
--color-transparent: rgb(255 255 0);
```

Should probably be 👇 

```
--color-transparent: rgb(0 0 0 / 0);
```
