### ISSUE TITLE
[Bug]: Specifying --path in the CLI uses wrong import paths for component dependencies

### ISSUE THREAD

**Issue by mattiasw** [untitleduico/react#123]
### Prerequisites

- [x] I have searched existing issues to ensure this bug hasn't been reported already
- [x] I have tested this with the latest version of the components

### Bug description

When using the CLI and specifying `--path` to install a component with dependencies (like `badges` or `tags`) somewhere else than in `components/`, the imports ignore the specified path. E.g., for `badges` the `dot-icon` import looks like this:

`import { Dot } from "@/components/foundations/dot-icon";`

instead of

`import { Dot } from "@/my-specified-path/foundations/dot-icon";`

### Steps to reproduce

1. Run `npx untitledui@latest add --path components/untitledui badges`
2. Have a look in `src/components/untitledui/base/badges/badges.tsx` and notice the `dot-icon` import.

### Expected behavior

The import in `badges.tsx` should be `import { Dot } from "@/components/untitledui/foundations/dot-icon";`, or possibly `import { Dot } from "../../foundations/dot-icon";`.

### Actual behavior

The import is `import { Dot } from "@/components/foundations/dot-icon";`.

### Code example

```tsx
npx untitledui@latest add --path components/untitledui badges
```

### Environment details

- OS: Ubuntu 25.10
- Node.js version: 22.14.0
- React version: 19.2.0
- Next.js version: 16.0.1
- Tailwind CSS version: 4.1.16

### Console errors

```shell

```

### Accessibility impact

- [ ] This bug affects keyboard navigation
- [ ] This bug affects screen reader users
- [ ] This bug affects focus management
- [ ] This bug affects color contrast or visual accessibility

**Comment by deebov** [comment]
Looking into this...

**Comment by deebov** [comment]
Hey @mattiasw, sorry it took so long to get back to this. But we've published a new latest version where this is fixed. Could you please try it again and confirm if it's fixed for you?

**Comment by mattiasw** [comment]
I can still reproduce the same issue using those two commands. Using version 0.1.54. (I think, because the `--version` flag seems to output the wrong value (0.1.53) but 0.1.54 is in the `~/.npm/_npx/.../untitledui/package.json`, and it said it installed 0.1.54 when I did the first `npx untitledui@latest add`.)

I don't have permission to reopen the issue.
